# Generated by Django 5.0.2 on 2024-07-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_otpcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
