# Generated by Django 5.0.2 on 2024-07-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_workouts"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="feeds")),
                ("title", models.CharField(max_length=200)),
                ("sub_title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name="workouts",
            name="vedio",
            field=models.FileField(upload_to="workouts"),
        ),
    ]
